---
title: "White Paper: Proposal for a design of Cylinder for plunger Control Valves"
format:
  html:
    self-contained: true
    toc: true
    toc-depth: 2
    toc-title: Contents
    number-sections: true
    number-depth: 3
    html-math-method: katex
    css: styles.css
reference-location: margin
---

# The purpose of this white paper

This "White paper" will help you understand the difficulties and simplify designing the cylinders for plunger valves. Discharge coefficients for flow through different multi-hole cylinders will be evaluated.

The calculations is based on the similarity of the control cylinders to the orifice plates. The model will be limited to turbulent flow models to predict velocities, pressure drop, cylinder discharge coefficient, and flow characteristics.

This document also presents a mathematical model for designing perforated cylinders that allow installed linear flow characteristics.

Later it will be necessary to carry out tests under laboratory conditions. The experimental results must be compared and analyzed to optimize the proposed models.

# Basic theory

## Volume and Surface Area of a Cylinder

A cylinder is a solid figure with two parallel circles of the same size at the top and bottom. The top and bottom of a cylinder are called bases. The height $h$ of a cylinder is the distance between the two bases. We will work with all the cylinders here. The sides and the height, $h$, will be perpendicular to the bases.

A cylinder has two circular bases of equal size. The height is the distance between the bases. For a cylinder, the area of the base, $B$, is the area of its circular base, $\pi \cdot r^2$. Therefore the volume of the cylinder is $V = B \cdot h$.

The distance around the edge of the cylinder is the circumference of the cylinder's base. It is also the length L of the rectangular area. The height of the cylinder is the width h of the rectangular area. So the area of the label can be represented as:

$$
  L = 2 \cdot \pi \cdot r \\
  A = 2 \cdot h \cdot \pi \cdot r
$$

## Valve Characteristics

### Inherent Control Valve Flow Characteristics:

The most common characteristics are shown in the figure above. The percent of flow through the valve is plotted against the valve stem position. The curves shown are typical of those available from valve manufacturers. These curves are based on the constant pressure drop across the valve and are called inherent flow characteristics.

-   **Linear** - flow capacity increases linearly with valve travel.
-   **Equal percentage** - flow capacity increases exponentially with valve trim travel. Equal increments of valve travel produce equal percentage changes in the existing $K_v$.
-   A **modified parabolic characteristic** is approximately midway between linear and equal-percentage characteristics. It provides fine throttling at low flow capacity and approximately linear characteristics at higher flow capacity.
-   Hyperbolic
-   Square Root

The majority of control applications are with valves with linear, equal-percentage, or modified-flow characteristics.

The inherent valve characteristics for an equal percentage valve are exponential and are usually simplified by valve manufacturers in the form:

$$
  f(x)= R^{(x-1)}
$$

where $R$ is a constant for the cylinder.

### Installed Control Valve Flow Characteristics

When valves are installed with pumps, piping and fittings, and other process equipment, the pressure drop across the valve will vary as the plug moves through its travel. The curve is called the Installed Flow Characteristic when the actual flow is plotted against the valve opening. In most applications, when the valve opens and the resistance due to fluid flow decreases, the pressure drop across the valve.

These are the differences between the inherent and installed characteristics of a control valve: - A linear curve as an inherent Flow characteristic will generally reflect an Installed Flow characteristic of a fast opening. - An equal percentage curve as inherent flow characteristics will generally reflect a linear Installed flow characteristic.

There is not one flow characteristic that is better than the other. It is your goal to achieve the desired characteristic.

**Linear installed Characteristics:**

-   Used in liquid level or flow loops.
-   Used in systems where the pressure drop across the valve is expected to remain relatively constant (i.e., steady-state systems).
-   Used when the pressure drop across the valve is a large proportion of the total pressure drop.

**Equal Percentage installed Characteristics:**

-   Used in processes where significant changes in pressure drop are expected.
-   Used in processes where the valve permits a small percentage of the total pressure drop.
-   Used in temperature and pressure control loops.

**Quick Opening installed Characteristics:**

-   Used for frequent on-off service.
-   Used for processes where "instantly" large flow is needed (i.e., safety systems or cooling water systems).

**Two rules of thumb for choosing the correct flow characteristic:**

-   If most pressure drops are taken through the valve and the upstream pressure is constant, a linear characteristic will better control.
-   If the piping and downstream equipment cause significant resistance to the system, the equal percentage will provide better control.

## Pressure losses through perforated plates
